
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import { Afacad } from 'next/font/google';


import "./globals.css";

const afacad = Afacad({
  subsets: ['latin'],
  weight: ['400','500','600','700'],      
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${afacad.className}  antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
            
          >
 <div  className="min-h-screen max-w-screen-2xl">
        {children}
        </div>
          </ThemeProvider>
       
      </body>
    </html>
  );
}
